export const myPeople = [
  {
    firstName: "Sue",
    lastName: "Bl",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "The Lark"],
    grade: "B+",
    notes: ["Barely know her but she's a good person", "Charity Worker"],
  },
  {
    firstName: "Leah",
    lastName: "Cop",
    birthMonth: "October",
    birthDay: 3,
    birthYear: 1970,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend", "Midwives"],
    grade: "A",
    notes: ["So Cool", "Crocheter"],
  },
  {
    firstName: "Helena",
    lastName: "Da.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: "Gram's Mom",
    groups: ["All", "Family"],
    grade: "A",
    notes: null,
  },
  {
    firstName: "Anne",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 13,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: "A",
    notes: null,
  },
  {
    firstName: "George",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 17,
    birthYear: 1941,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: "B",
    notes: null,
  },
  {
    firstName: "Diane",
    lastName: "DeP.",
    birthMonth: "March",
    birthDay: 21,
    birthYear: 1942,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: "D+",
    notes: null,
  },
  {
    firstName: "Pat",
    lastName: "DeP.",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1974,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: "C",
    notes: null,
  },
  {
    firstName: "Jeff",
    lastName: "Hains",
    birthMonth: "January",
    birthDay: 20,
    birthYear: 1986,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: "A",
    notes: null,
  },
  {
    firstName: "Rita",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 28,
    birthYear: 1919,
    passedAway: "September 5, 2012",
    comment: "Gram  -Best person ever",
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Pat",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 1981,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Mike",
    lastName: "Hen.",
    birthMonth: "March",
    birthDay: 9,
    birthYear: 1984,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Jack",
    lastName: "Hen.",
    birthMonth: "April",
    birthDay: 14,
    birthYear: 1987,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Daniel",
    lastName: "Hen.",
    birthMonth: "July",
    birthDay: 27,
    birthYear: 1988,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Marty",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 2,
    birthYear: 1948,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Maureen",
    lastName: "Hen.",
    birthMonth: "June",
    birthDay: 18,
    birthYear: 1956,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "John",
    lastName: "Hen.",
    birthMonth: "November",
    birthDay: 6,
    birthYear: 1916,
    passedAway: "8/9/69",
    comment: "Grandfather",
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Rose",
    lastName: "Hen.",
    birthMonth: "September",
    birthDay: 27,
    birthYear: 2023,
    passedAway: null,
    comment: "Daniel's Kid",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Katherine",
    lastName: "How.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "John",
    lastName: "How.",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Edith",
    lastName: "I.",
    birthMonth: "March",
    birthDay: 22,
    birthYear: 1992,
    passedAway: null,
    comment: "Bird, my niece!",
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Christine",
    lastName: "I.",
    birthMonth: "March",
    birthDay: 27,
    birthYear: 1966,
    passedAway: null,
    comment: "Sister, cool",
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Michael",
    lastName: "I.",
    birthMonth: "July",
    birthDay: 5,
    birthYear: 1967,
    passedAway: null,
    comment: "Me, the guy doing this shit!",
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Shekar",
    lastName: "I.",
    birthMonth: "July",
    birthDay: 15,
    birthYear: 1963,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Kamal",
    lastName: "I.",
    birthMonth: "July",
    birthDay: 28,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Mary",
    lastName: "I.",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1944,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Bharathi",
    lastName: "I.",
    birthMonth: "November",
    birthDay: 14,
    birthYear: 1958,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Yogesh",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 20,
    birthYear: 2006,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Ramanath",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 25,
    birthYear: 1933,
    passedAway: "1/12/16",
    comment: null,
    groups: ["My People", "All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Balan",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 30,
    birthYear: 1964,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Kuti",
    lastName: "I.",
    birthMonth: "February",
    birthDay: 18,
    birthYear: 1958,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Eshi",
    lastName: "I.",
    birthMonth: "February",
    birthDay: 19,
    birthYear: 1954,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Bharathi",
    lastName: "I.",
    birthMonth: "February",
    birthDay: 2,
    birthYear: 1961,
    passedAway: null,
    comment: "Balan's wife",
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Amba",
    lastName: "I.",
    birthMonth: "December",
    birthDay: 12,
    birthYear: 1954,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Carolyn",
    lastName: "I.",
    birthMonth: "August",
    birthDay: 24,
    birthYear: 1973,
    passedAway: null,
    comment: null,
    groups: ["Pet", "My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Franky",
    lastName: "I.",
    birthMonth: "September",
    birthDay: 11,
    birthYear: 2023,
    passedAway: null,
    comment: null,
    groups: ["My People", "All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Mary",
    lastName: "Kel",
    birthMonth: "June",
    birthDay: 12,
    birthYear: 1923,
    passedAway: "8/11/2008",
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Robert",
    lastName: "Kel",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Christine",
    lastName: "Lar",
    birthMonth: "January",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
    comment: "Aunt Cis",
    groups: ["All", "Deceased", "The Lark", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Courtney",
    lastName: "Lar",
    birthMonth: "January",
    birthDay: 12,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "The Lark", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Riley ",
    lastName: "L",
    birthMonth: "October",
    birthDay: 14,
    birthYear: 2009,
    passedAway: null,
    comment: null,
    groups: ["All", "The Lark", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Eleanor",
    lastName: "L",
    birthMonth: "July",
    birthDay: 6,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "The Lark", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "John, Jr.",
    lastName: "Lar",
    birthMonth: "July",
    birthDay: 10,
    birthYear: 2006,
    passedAway: null,
    comment: null,
    groups: ["All", "The Lark", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "John",
    lastName: "Lar",
    birthMonth: "September",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "The Lark", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Jake",
    lastName: "McN",
    birthMonth: "December",
    birthDay: 22,
    birthYear: 1969,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Oscar",
    lastName: "McN",
    birthMonth: "February",
    birthDay: 16,
    birthYear: 2004,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Razel",
    lastName: "McN",
    birthMonth: "May",
    birthDay: 31,
    birthYear: 2001,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Josiah",
    lastName: "Mur",
    birthMonth: "January",
    birthDay: 14,
    birthYear: 1971,
    passedAway: null,
    comment: "Al Olander, Count Fuckula",
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Kai",
    lastName: "P.W.",
    birthMonth: "February",
    birthDay: 25,
    birthYear: 1987,
    passedAway: null,
    comment: "Bird's Husband",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Louisa",
    lastName: "Rad",
    birthMonth: "October",
    birthDay: 17,
    birthYear: 2001,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Naomi",
    lastName: "Rad",
    birthMonth: "July",
    birthDay: 21,
    birthYear: 1999,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Jonathon",
    lastName: "Rad",
    birthMonth: "December",
    birthDay: 31,
    birthYear: 1965,
    passedAway: null,
    comment: "Priestman",
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Marino",
    lastName: "Ros",
    birthMonth: "September",
    birthDay: 16,
    birthYear: 1961,
    passedAway: null,
    comment: "Annie's Italian Boyfriend",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Lynne",
    lastName: "Row",
    birthMonth: "December",
    birthDay: 21,
    birthYear: 1965,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Oliver",
    lastName: "Roy",
    birthMonth: "January",
    birthDay: 21,
    birthYear: 2001,
    passedAway: null,
    comment: "My Nephew, a Mango",
    groups: ["All", "Family", "My People"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Paul",
    lastName: "Roy",
    birthMonth: "August",
    birthDay: 4,
    birthYear: null,
    passedAway: null,
    comment: "Sis's Cat",
    groups: ["All", "Family", "My People"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Andrey",
    lastName: "Roy",
    birthMonth: "January",
    birthDay: 30,
    birthYear: 1988,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Danika",
    lastName: "Roy",
    birthMonth: "March",
    birthDay: 10,
    birthYear: 2022,
    passedAway: null,
    comment: null,
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Lorelei",
    lastName: "Roy",
    birthMonth: "June",
    birthDay: 25,
    birthYear: 2018,
    passedAway: null,
    comment: "Lolo",
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Ophelia",
    lastName: "Roy",
    birthMonth: "August",
    birthDay: 22,
    birthYear: 2022,
    passedAway: null,
    comment: "Fifi",
    groups: ["All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Carol",
    lastName: "Sit",
    birthMonth: "January",
    birthDay: 31,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Naomi",
    lastName: "Ske",
    birthMonth: "November",
    birthDay: 11,
    birthYear: 2008,
    passedAway: null,
    comment: "Livia's kid 1",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Fiona",
    lastName: "Ske",
    birthMonth: "March",
    birthDay: 31,
    birthYear: 2010,
    passedAway: null,
    comment: "Livia's kid 2",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Luna",
    lastName: "Ske",
    birthMonth: "March",
    birthDay: 4,
    birthYear: 2011,
    passedAway: null,
    comment: "Selena's kid 1",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Leo",
    lastName: "Ske",
    birthMonth: "July",
    birthDay: 24,
    birthYear: 2010,
    passedAway: null,
    comment: "Selena's kid 2",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Billie",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 2,
    birthYear: 1931,
    passedAway: "October 27, 2022",
    comment: "The Good William",
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Bertha",
    lastName: "Ske",
    birthMonth: null,
    birthDay: null,
    birthYear: 1882,
    passedAway: 1968,
    comment: "Bertha was born in 1882 and died in 1968?",
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Joseph",
    lastName: "Ske",
    birthMonth: "January",
    birthDay: 6,
    birthYear: 1923,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Roger",
    lastName: "Ske",
    birthMonth: "July",
    birthDay: 26,
    birthYear: 1926,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Pamela",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 1956,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Selena",
    lastName: "Ske",
    birthMonth: "May",
    birthDay: 21,
    birthYear: 1978,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Livia",
    lastName: "Ske",
    birthMonth: "September",
    birthDay: 10,
    birthYear: 1980,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Tony",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 2002,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Isabel",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: 2002,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Patrick, Jr.",
    lastName: "Ske",
    birthMonth: "August",
    birthDay: 9,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Patrick",
    lastName: "Ske",
    birthMonth: "September",
    birthDay: 11,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Maryanne",
    lastName: "Ske",
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Laura",
    lastName: "Wil",
    birthMonth: "December",
    birthDay: 31,
    birthYear: 1967,
    passedAway: null,
    comment: null,
    groups: ["T'sut", "All", "Friend"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Len",
    lastName: "Wil",
    birthMonth: "August",
    birthDay: 29,
    birthYear: 1937,
    passedAway: "March 17, 2025",
    comment: "Laura's Dad - A good man",
    groups: ["T'sut", "All", "Deceased"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Jesus H.",
    lastName: "Christ",
    birthMonth: "December",
    birthDay: 25,
    birthYear: "BC 0005",
    passedAway: "AD 0033",
    comment: "Who really knows dates when it comes to this mysterious dude?",
    groups: ["Holiday People", "All", "Deceased"],
    grade: "C-",
    notes: null,
  },
  {
    firstName: "Easter Bunny",
    lastName: "Jones",
    birthMonth: "April",
    birthDay: "Fluctuating date",
    birthYear: "Unknown Year",
    passedAway: "Unknown Year",
    comment: "This happy bastard loves hopping around like a fool",
    groups: ["Holiday People", "All", "Deceased"],
    grade: null,
    notes: null,
  },
  {
    firstName: "XXXXX",
    lastName: "XXXXX",
    birthMonth: "April",
    birthDay: "Fluctuating date",
    birthYear: "1900",
    passedAway: "2025",
    comment: "XXXXXXX",
    groups: ["All", "Deceased"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Dick",
    lastName: "Beniña",
    birthMonth: "July",
    birthDay: "7",
    birthYear: "2026",
    passedAway: "null",
    comment: "A Great Guy",
    groups: ["All", "Family"],
    grade: null,
    notes: null,
  },
  {
    firstName: "Count",
    lastName: "Dracula",
    birthMonth: "July",
    birthDay: "11",
    birthYear: "1026",
    passedAway: "1532",
    comment: "You Were A Bloody Mess",
    groups: ["All", "Deceased", "Family"],
    grade: null,
    notes: null,
  },
];
