export const myPeople = [
  {
    firstName: null,
    lastName: null,
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: null,
    grade: null,
    notes: null,
  },
  {
    firstName: null,
    lastName: null,
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: null,
    grade: null,
    notes: null,
  },
  {
    firstName: null,
    lastName: null,
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: null,
    grade: null,
    notes: null,
  },
  {
    firstName: null,
    lastName: null,
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: null,
    grade: null,
    notes: null,
  },
  {
    firstName: null,
    lastName: null,
    birthMonth: null,
    birthDay: null,
    birthYear: null,
    passedAway: null,
    comment: null,
    groups: null,
    grade: null,
    notes: null,
  },
];
